-- Добавляем недостающие колонки в таблицу promos
ALTER TABLE promos ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE promos ADD COLUMN IF NOT EXISTS discount NUMERIC(5,2) DEFAULT 0;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE promos ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE promos ADD COLUMN IF NOT EXISTS conditions JSONB DEFAULT '{"type":"all"}'::jsonb;
ALTER TABLE promos ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
