CREATE TABLE IF NOT EXISTS timesheet (id BIGINT PRIMARY KEY, user_id UUID, employee_id BIGINT, employee_name TEXT DEFAULT '', date DATE, hours NUMERIC DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS deductions (id BIGINT PRIMARY KEY, user_id UUID, name TEXT DEFAULT '', amount NUMERIC DEFAULT 0, employee_id BIGINT, date TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS bonuses (id BIGINT PRIMARY KEY, user_id UUID, name TEXT DEFAULT '', amount NUMERIC DEFAULT 0, employee_id BIGINT, date TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS plans (id BIGINT PRIMARY KEY, user_id UUID, name TEXT DEFAULT '', target_amount NUMERIC DEFAULT 0, target_type TEXT DEFAULT '', period TEXT DEFAULT 'month', year INTEGER, created_at TIMESTAMPTZ DEFAULT NOW());
GRANT ALL ON ALL TABLES IN SCHEMA public TO atlaspos;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO atlaspos;
